<?php

namespace Tests\Feature\Auth;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use Illuminate\Support\Str;

class RegistrationTest extends TestCase
{
    // This trait ensures that the database is refreshed before each test,
    // meaning that data from one test does not affect another.
    use RefreshDatabase;

    /**
     * Test that the registration screen can be accessed.
     * This checks if visiting '/register' returns a 200 status code.
     */
    public function test_registration_screen_can_be_rendered(): void
    {
        // Send a GET request to the registration page.
        $response = $this->get('/register');

        // Assert that the response status is 200 (OK), meaning the page loads successfully.
        $response->assertStatus(200);
    }

    /**
     * Test that new users can successfully register.
     * This test runs multiple times with different data from the userDataProvider method.
     *
     * @dataProvider userDataProvider
     */
    public function test_new_users_can_register($name, $email, $password, $role): void
    {
        // Simulate a POST request to register a new user.
        $response = $this->post('/register', [
            'name' => $name,
            'email' => $email,
            'password' => $password,
            'password_confirmation' => $password, // Ensures password confirmation matches
            'role' => $role,
        ]);

        // Assert that the user is authenticated after successful registration.
        $this->assertAuthenticated();

        // Assert that after registration, the user is redirected to the dashboard.
        $response->assertRedirect(route('dashboard', absolute: false));
    }

    /**
     * Provides test data for test_new_users_can_register.
     *
     * The @dataProvider annotation makes PHPUnit run the test 1000 times,
     * each time with a different user generated by this method.
     *
     * @return array[] Each entry is a dataset passed to the test method.
     */
    public static function userDataProvider(): array
    {
        $users = [];

        // Generate 20 different users
        for ($i = 1; $i <= 1000; $i++) {
            $users[] = [
                'Test User ' . $i, // Unique name
                'test' . $i . '@example.com', // Unique email
                'password', // Simple static password (in a real app, use hashing!)
                $i % 2 === 0 ? 'admin' : 'user' // Alternates between 'admin' and 'user'
            ];
        }

        // Each entry in this array is passed to the test method above
        // So test_new_users_can_register() runs 20 times
        return $users; // Returns an array of 20 different users
    }
}
